apiVersion: v1
kind: ConfigMap
metadata:
  name: paper-service-config
  labels:
    app: paper-service
data:
  SPRING_FLYWAY_URL: "jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/paper"
  SPRING_FLYWAY_USER: "paper"
  SPRING_FLYWAY_PASSWORD: "paper"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/paper"
  SPRING_DATASOURCE_USERNAME: "paper"
  SPRING_DATASOURCE_PASSWORD: "paper"
  STORAGE_PURGATORY_PATH: "/usr/local/storage/purgatory"
  STORAGE_ISSUES_PATH: "/usr/local/storage/issues"