apiVersion: v1
kind: ConfigMap
metadata:
  name: paper-service-config
  labels:
    app: paper-service
data:
  SPRING_FLYWAY_URL: "jdbc:postgresql://192.168.2.49:30327/paper"
  SPRING_FLYWAY_USER: "paper"
  SPRING_FLYWAY_PASSWORD: "paper"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://192.168.2.49:30327/paper"
  SPRING_DATASOURCE_USERNAME: "paper"
  SPRING_DATASOURCE_PASSWORD: "paper"